name: "claude-sonnet-4-labels"
description: "Anthropic Claude Sonnet 4 for group labeling"
provider: "anthropic"
model: "claude-sonnet-4-20250514"
type: "labels"
version: "1.0"

# Model parameters
parameters:
  max_tokens: 1000
  temperature: 0.7  # Higher for creative labeling
  top_p: 0.9

# Custom prompt template (optional override)
# Available variables:
  # - {category} - The verbal fluency category
  # - {groups_text} - Formatted groups ("Group 1: cat, dog\nGroup 2: fish, bird")
  # - {num_groups} - Number of groups to label

prompt_template: null  # Use default

# Metadata
created_date: "2025-01-14"
author: "mariana"
notes: "High-quality model for descriptive group labeling with high temperature"

# Expected output format
output_format:
  type: "json"
  schema:
    group_labels:
      - group_number: "integer"
        words: "array of strings"
        label: "string"